export const UPDATE_FINANCIALS = 'UPDATE_FINANCIALS';
export const UPDATE_POSTS = "UPDATE_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const SET_CURRENT_FINANCIAL = 'SET_CURRENT_FINANCIAL';
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_FINANCIAL = 'ADD_FINANCIAL';
export const ADD_POST = "ADD_POST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
